### ISSUE TITLE
dugneonCompWeight returns NaN when passing M7 value

### ISSUE THREAD

**Issue by dukio** [Antonio32A/lilyweight#12]
[dungeonCompWeight.js](https://github.com/Antonio32A/lilyweight/blob/master/lib/dungeonCompWeight.js) is returning NaN when passed a value for M7 completions.

I didn't test but it's most likely due to the missing value for M7 in this array:
https://github.com/Antonio32A/lilyweight/blob/59106ddc75b24606888ff4f4c98455bd3b0c7d8f/lib/constants.json#L68-L83

**Comment by Antonio32A** [comment]
That's probably because lilyweight hasn't updated to support M7 yet, @LappySheep needs to pick a value for it first.

**Comment by dukio** [comment]
Uhm that's weight cause in the discord it seems like it's counting M7:

![image](https://user-images.githubusercontent.com/2744227/156667729-e352338b-b74e-40bb-93e3-5fa37b0eb8f6.png)

the dungeon weight is higher that what it's supposed to be if calculated ignoring M7

**Comment by Antonio32A** [comment]
I don't think that @LappySheep pushed to https://github.com/LappySheep/hypixel-skyblock-weight yet. 
This lib will be updated as soon as the main repository gets updated.

**Comment by dukio** [comment]
Actually nevermind... the dungeon weight is different for my profile too, and I never attempted M7... probably just very outdated values

**Comment by Antonio32A** [comment]
Sorry for the wait, was a bit busy and wasn't keeping up with the original repository.
@Desco1 pushed v2.4.0 which adds those changes, https://github.com/Antonio32A/lilyweight/commit/68381759caac8c803cfbfc0560dde9365518978e.
