### ISSUE TITLE
types missing for m7?

### ISSUE THREAD

**Issue by dukio** [Antonio32A/lilyweight#14]
https://github.com/Antonio32A/lilyweight/blob/a3904716f1f9159c1597e90a066f56ebbe5e4c2f/lib/index.d.ts#L28

Seems like types for mCataCompl are missing the 7th floor

**Comment by Antonio32A** [comment]
Fixed in https://github.com/Antonio32A/lilyweight/commit/29b1dafd4ecd15cc0aaae633342b578a9b07b534
